# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=30, null=True)),
                ('blog_subtitle', models.CharField(max_length=30, null=True)),
                ('blog_text', models.CharField(max_length=8000, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('picture_location', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
