# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import foow.models


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_text',
            field=models.CharField(default=foow.models.defaultText, max_length=2000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default=foow.models.defaultTitle, max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 18, 50, 46, 798867, tzinfo=utc), verbose_name='date published'),
        ),
    ]
