# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0002_auto_20160928_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 18, 51, 9, 424937, tzinfo=utc)),
        ),
    ]
