# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0002_auto_20161027_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='mod_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 8, 55, 8, 172696, tzinfo=utc), editable=False),
        ),
    ]
