# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0003_auto_20160928_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_subtitle',
            field=models.CharField(default='Default SubTitle', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_text',
            field=models.CharField(default='Default Text', max_length=8000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='Default Title', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 13, 30, 40, 263524, tzinfo=utc)),
        ),
    ]
