# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0007_auto_20161110_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='picture_location',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
