# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0008_auto_20161110_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_subtitle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
