# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0009_auto_20161111_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_text',
            field=models.CharField(default='blog text', max_length=10000),
        ),
    ]
