# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:31
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0011_auto_20161111_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_subtitle',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\cmg1229\\Documents\\DjangoProjects\\CMGPortal/media'), upload_to=''),
        ),
    ]
