# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 12:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0012_auto_20161116_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('hit_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_ip', models.CharField(max_length=72)),
                ('hit_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/cmg1229/DjangoProjects/CMGPortal/media'), upload_to=b''),
        ),
    ]
