# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 09:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foow', '0013_auto_20161213_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=72)),
                ('album_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-album_created'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_description', models.CharField(max_length=500, null=True)),
                ('picture', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/Users/cmg1229/DjangoProjects/CMGPortal/media'), upload_to=b'')),
                ('thumbnail', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/Users/cmg1229/DjangoProjects/CMGPortal/media'), upload_to=b'')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foow.Album')),
            ],
        ),
    ]
